services:
  - type: web
    name: ozkiz-studio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NOTION_API_KEY
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: NOTION_NAME_PROPERTY
        value: 제품명
